name: Docker

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v1.0.2
    - uses: docker/setup-buildx-action@v1.1.2
    - name: Docker login
      uses: docker/login-action@v1.8.0
      with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

    
    - name: Build and Push the Docker image
      uses: docker/build-push-action@v2.4.0
      with:
          context: ./igotolib-person
          platforms: linux/arm64,linux/amd64
          push: true
          tags: shiguang2/igotolib-person:latest
